service: aws-lambda-model

provider:
  name: aws
  runtime: python3.10
  memorySize: 512  # Increase memory for Pandas & XGBoost
  timeout: 30  # Set timeout to 30s to prevent Athena failures
  iamRoleStatements:
    - Effect: 'Allow'
      Action: "*"
      Resource: "*"

plugins:
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  predict:
    handler: handler.main
    events:
      - http:
          path: predict
          method: post
